DELIMITER $$

CREATE PROCEDURE testInsertarFactura(
 
 IN p_DNI VARCHAR(11),
 IN p_MATRICULA VARCHAR(5),
 IN p_FECHA_VENTA DATE,
 IN p_IMPUESTO float

)

BEGIN 

DECLARE v_NUMERO INT;

START TRANSACTION;

SELECT MAX(NUMERO)+1 INTO v_NUMERO FROM FACTURAS;

INSERT INTO facturas(DNI, MATRICULA, FECHA_VENTA, NUMERO, IMPUESTO)
VALUES (p_DNI,p_MATRICULA,p_FECHA_VENTA,v_NUMERO,p_IMPUESTO);

COMMIT;

SELECT CONCAT('Factura ',v_NUMERO, ' ha sido insertada con exito' ) AS mensaje;

END $$


DELIMITER ;


CALL testInsertarFactura('1471156710', '00236', '2025-05-19', 0.15);